spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:6789/arabyte-database
    username: myuser
    password: mypassword
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 7e638b59742ba8c811732dfbd84648fd
            client-secret:
            redirect-uri: http://localhost:8080/api/auth/kakao/callback
            authorization-grant-type: authorization_code
            client-authentication-method: post
            scope:
              - name
              - profile_nickname
              - profile_image
              - account_email
              - gender
              - age_range
              - birthday
              - birthyear
              - phone_number
    jwt:
      secret-key: "ArabyteSecretKeyForJwtTokenGeneration"
      access-token-expiration-ms: 30000 # 만료시간 1시간
      refresh-token-expiration-ms: 1209600000 # 만료시간 2주