spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:6789/arabyte-database
    username: myuser
    password: mypassword

ocr:
  server:
    base-url: https://arabyte-ocr.fly.dev