spring:
  liquibase:
    change-log: classpath:db/changelog-master.yaml
    enabled: true
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            client-authentication-method: post
            scope:
              - name
              - profile_nickname
              - profile_image
              - account_email
              - gender
              - age_range
              - birthday
              - birthyear
              - phone_number
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      access-token-expiration-ms: 30000 # 만료시간 1시간
      refresh-token-expiration-ms: 1209600000 # 만료시간 2주

springdoc:
  swagger-ui:
    tags-sorter: alpha
    operations-sorter: method