spring:
  liquibase:
    change-log: classpath:db/changelog-master.yaml
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:6789/arabyte-database
    username: myuser
    password: mypassword
